client:
  rest:
    feign:
      coingecko:
        url: https://api.coingecko.com/api/v3
spring:
  application:
    name: "bitoc-trading"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
